language: python
python:
  - "3.6"
install:
  - git submodule init
  - pip install geojson -t functions/fetch/ChinaAQIData
  - pip install requests -t functions/fetch
script: true
after_success: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_REGION && ./apex deploy